name: AgendaLuz
description: "Aplicativo de agendamento e controle financeiro para profissionais autônomos."
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon.png
    # adicione outras imagens caso necessário:
    # - assets/img/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/img/icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
